!1.0.0
meta:
  id: consumer-offset
  revision: 2
key: consumer-offset
status:
  resolution: InsufficientResources
  replicaMap: {}
  mirrorMap: {}
  reason: ''
spec:
  replicas: !computed
    partitions: 1
    replicationFactor: 1
    ignoreRackAssignment: false
  cleanupPolicy: !segment
    timeInSeconds: 604800
  storage:
    segmentSize: 512000000
    maxPartitionSize: 2048000000
  compressionType: Any
  system: true
