[package]
name = "example-tls-rustls-async-reload"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
rustls = "0.23.9"
salvo = { workspace = true, features = ["rustls"] }
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
