[aws]

[aws.dynamo]
user_settings_table = "core-user-settings-main"

[kafka]
[kafka.hit_stream]
topic = "hit-stream-main"
hosts = ["localhost:9092", "localhost:9093"]

[kafka.click_aggs]
topic = "click-aggs-local"
hosts = ["localhost:9092", "localhost:9093"]
ack_timeout_secs = 60


[fluvio]
[fluvio.hit_stream]
topic = "hit-stream-main"
host = "localhost:9003"

[fluvio.click_aggs]
topic = "click-aggs-local"
host = "localhost:9003"
batch_size = 100
linger = 500

[moka]
[moka.user_settings_cache]
max_capacity = 10_000
time_to_live_minutes = 60
time_to_idle_minutes = 20

[uaparser]
yaml = "../data/ua-parser/user-agents.yaml"

[geo_ip]
mmdb = "../data/geo-ip/GeoLite2-Country.mmdb"

[redis]
initial_nodes = ["redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@cache"]
password = "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"

[server]
threads = 8
listen_os_signals = true
exit = true
