debug = true

[aws]
local = true
localstack_endpoint = "http://localhost:4566"

[aws.dynamo]
encryption_table = "core-routes-encryption-local"
routes_table = "core-routes-local"
hostname_mappings_table = "core-routes-hostname-mapping-local"
user_settings_table = "core-user-settings-local"


[kafka]
[kafka.hit_stream]
topic = "hit-stream-local"
hosts = ["kafka:9092", "kafka:9093"]

[kafka.click_aggs]
topic = "click-aggs-local"
hosts = ["kafka:9092", "kafka:9093"]
ack_timeout_secs = 60

[fluvio]
[fluvio.hit_stream]
topic = "hit-stream-local"
host = "localhost:9103"
consumer = "tracker"

[fluvio.click_aggs]
topic = "click-aggs-local"
host = "localhost:9103"
linger_millis = 200
batch_size = 16536


[uaparser]
yaml = "./data/ua-parser/regexes.yaml"

[geo_ip]
mmdb = "./data/geo-ip/GeoLite2-Country.mmdb"

[redis]
host = "redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@cache"
password = "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
