debug = true

[aws]
local = true
localstack_endpoint = "http://localhost:4566"

[aws.dynamo]
encryption_table = "core-routes-encryption-local"
routes_table = "core-routes-local"
hostname_mappings_table = "core-routes-hostname-mapping-local"
user_settings_table = "core-user-settings-local"

[kafka]
[kafka.hit_stream]
topic = "hit-stream-local"
hosts = ["localhost"]

[kafka.click_aggs]
topic = "click-aggs-local"
hosts = ["localhost:9092", "localhost:9093"]
ack_timeout_secs = 60


[fluvio]
[fluvio.hit_stream]
topic = "hit-stream-main"
host = "localhost:9003"

[fluvio.click_aggs]
topic = "click-aggs-local"
host = "localhost:9003"
batch_size = 100
linger = 500

[uaparser]
yaml = "../data/ua-parser/regexes.yaml"

[geo_ip]
mmdb = "../data/geo-ip/GeoLite2-Country.mmdb"

[redis]
initial_nodes = ["redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@cache"]
password = "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
