[aws]

[aws.dynamo]
encryption_table = "core-routes-encryption-local"
routes_table = "core-routes-local"
hostname_mappings_table = "core-routes-hostname-mapping-local"
user_settings_table = "core-user-settings-local"

# Mongodb Configuration
[mongodb]
connection_string = "mongodb://localhost:27017"
database_name = "click_router"
routes_collection = "routes"
crypto_collection = "crypto"
user_settings_collection = "user_settings"

[server]
threads = 8
listen_os_signals = true
exit = true
port = 3000
