[server]
port = 5810

[aws]
local = false

[aws.dynamo]
encryption_table = "core-routes-encryption-main"
routes_table = "core-routes-main"
hostname_mappings_table = "core-routes-hostname-mapping-main"
user_settings_table = "core-user-settings-main"

[mongodb]
connection_string = "mongodb://root:example@mongo:27017/"
database_name = "shortas"
routes_collection = "core_routes_main"
crypto_collection = "core_routes_encryption_main"
user_settings_collection = "core_user_settings_main"

[rabbitmq]
uri = "amqp://guest:guest@rabbitmq:5672/%2f"
route_exchange = "cache.invalidation.routes"
user_settings_exchange = "cache.invalidation.user_settings"
