[package]
name = "domains"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
# Workspace dependencies
tokio.workspace = true
tracing-subscriber.workspace = true

# Project-specific dependencies
salvo = { path = "../../../salvo/crates/salvo", features = [
    "anyhow",
    "proxy",
    "rustls",
    "quinn",
    "test",
    "logging",
] }
