[package]
name = "click-tracker"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
anyhow.workspace = true
async-trait.workspace = true
signal-hook.workspace = true
tokio.workspace = true
tokio-util.workspace = true
typed-builder.workspace = true
aws-config.workspace = true
aws-sdk-dynamodb.workspace = true
aws-sdk-kinesis.workspace = true
chrono.workspace = true
redis.workspace = true
tracing.workspace = true
moka.workspace = true
uaparser.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
maxminddb.workspace = true
ulid.workspace = true
kafka.workspace = true
clap.workspace = true
tracing-subscriber.workspace = true
dotenv.workspace = true
config.workspace = true
fluvio.workspace = true
tokio-graceful-shutdown.workspace = true
flume.workspace = true
futures.workspace = true
mongodb.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "user_agent_parsing"
harness = false

[[bench]]
name = "aggregate_module"
harness = false

[[bench]]
name = "context_creation"
harness = false

[[bench]]
name = "full_pipeline"
harness = false
