[package]
name = "click-router"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "A click redirection server."
readme = "../README.md"
keywords = ["shortas", "router", "fast", "http", "redirect"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
accept-language.workspace = true
anyhow.workspace = true
async-trait.workspace = true
aws-config.workspace = true
aws-sdk-dynamodb.workspace = true
aws-sdk-kinesis.workspace = true
chrono.workspace = true
clap.workspace = true
config.workspace = true
dotenv.workspace = true
dyn-clone.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
maxminddb.workspace = true
moka.workspace = true
rand.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_dynamo.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower.workspace = true
tracing.workspace = true
uaparser.workspace = true
urlencoding.workspace = true
rustls.workspace = true
tracing-subscriber.workspace = true
cookie.workspace = true
multimap.workspace = true
indexmap.workspace = true
uuid.workspace = true
kafka.workspace = true
ulid.workspace = true
rdkafka.workspace = true
fluvio.workspace = true
typed-builder.workspace = true
hyper-rustls.workspace = true
fastrand.workspace = true
percent-encoding.workspace = true
string_format.workspace = true
futures.workspace = true
mongodb.workspace = true
lapin.workspace = true
prometheus.workspace = true
lazy_static.workspace = true
qrcode.workspace = true
image.workspace = true

# Project-specific dependencies
salvo = { path = "../../salvo/crates/salvo", features = [
    "anyhow",
    "proxy",
    "rustls",
    "quinn",
    "test",
    "logging",
] }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "default"
harness = false

[[bench]]
name = "optimizations"
harness = false

[[bench]]
name = "redirect_processing"
harness = false
