# sources:
#   click_stream:
#     type: kafka
#     auto_offset_reset: smallest
#     bootstrap_servers: kafka:9092
#     group_id: vector
#     topics: 
#       - "click-aggs-local"
#     decoding:
#       codec: bytes


# sinks:
#   clickhouse:
#     type: "clickhouse"
#     inputs: 
#       - "click_stream"
#     endpoint: "http://clickhouse:8123"
#     database: "shortas"
#     table: "click_stream_raw"
#     skip_unknown_fields: true
#     batch:
#       timeout_secs: 1
#     buffer:
#       max_events: 10000
      
sources:
  click_stream:
    type: kafka
    auto_offset_reset: smallest
    bootstrap_servers: kafka:9092
    group_id: vector
    topics: 
      - "click-aggs-local"
    decoding:
      codec: json

sinks:
  clickhouse:
    type: "clickhouse"
    inputs: 
      - "click_stream"
    endpoint: "http://clickhouse:8123"
    database: "shortas"
    table: "click_stream"
    date_time_best_effort: true
    skip_unknown_fields: true
    batch:
      timeout_secs: 1
    buffer:
      max_events: 10000

  my_sink_id:
    type: console
    inputs:
      - click_stream
    target: stdout
    encoding:
      codec: json
