[package]
name = "route-verifier"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
# Workspace dependencies
salvo.workspace = true
tracing-subscriber.workspace = true
tracing-loki.workspace = true
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
config.workspace = true
derive_more.workspace = true
dotenv.workspace = true
dyn-clone.workspace = true
env_logger.workspace = true
mongodb.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
chrono.workspace = true
lapin.workspace = true
uuid.workspace = true
tokio-graceful-shutdown.workspace = true
futures.workspace = true
reqwest.workspace = true
url.workspace = true
urlencoding.workspace = true
