[aws]

[aws.dynamo]
encryption_table = "core-routes-encryption-main"
routes_table = "core-routes-main"
hostname_mappings_table = "core-routes-hostname-mapping-main"
user_settings_table = "core-user-settings-main"

[kafka]
[kafka.hit_stream]
topic = "hit-stream-main"
hosts = ["localhost:9092", "localhost:9093"]
ack_timeout_secs = 60
batch_size = 100
consumers_count = 2
iteration_seconds = 1

[fluvio]
[fluvio.hit_stream]
topic = "hit-stream-main"
host = "localhost:9003"
batch_size = 100
linger = 500

[moka]
[moka.crypto_cache]
max_capacity = 10_000
time_to_live_minutes = 60
time_to_idle_minutes = 20

[moka.routes_cache]
max_capacity = 10_000
time_to_live_minutes = 60
time_to_idle_minutes = 20

[moka.user_settings_cache]
max_capacity = 10_000
time_to_live_minutes = 60
time_to_idle_minutes = 20

[uaparser]
yaml = "../data/ua-parser/user-agents.yaml"

[geo_ip]
mmdb = "../data/geo-ip/GeoLite2-Country.mmdb"

[server]
threads = 8
listen_os_signals = true
exit = true
