[aws]
local = false

[aws.dynamo]
encryption_table = "core-routes-encryption-main"
routes_table = "core-routes-main"
hostname_mappings_table = "core-routes-hostname-mapping-main"
user_settings_table = "core-user-settings-main"

[uaparser]
yaml = "./data/ua-parser/user-agents.yaml"

[geo_ip]
mmdb = "./data/geo-ip/GeoLite2-Country.mmdb"