[aws]
local = false

[aws.dynamo]
encryption_table = "core-routes-encryption-main"
routes_table = "core-routes-main"
hostname_mappings_table = "core-routes-hostname-mapping-main"
user_settings_table = "core-user-settings-main"

[aws.kinesis]
[aws.kinesis.hit_stream]
stream_name = "hit-stream-main"
partition_keys = ["hit-stream_01", "hit-stream_02"]
batch_size = 100
consumers_count = 2
iteration_seconds = 1

[uaparser]
yaml = "./data/ua-parser/user-agents.yaml"

[geo_ip]
mmdb = "./data/geo-ip/GeoLite2-Country.mmdb"