debug = true

[aws]
local = true
localstack_endpoint = "http://localhost:4566"

[aws.dynamo]
encryption_table = "core-routes-encryption-local"
routes_table = "core-routes-local"
hostname_mappings_table = "core-routes-hostname-mapping-local"
user_settings_table = "core-user-settings-local"

[kafka]
[kafka.hit_stream]
topic = "hit-stream-main"
hosts = ["localhost"]
ack_timeout_secs = 60
batch_size = 100
consumers_count = 2
iteration_seconds = 1


[fluvio]
[fluvio.hit_stream]
topic = "hit-stream-local"
host = "sc:9103"
batch_size = 100
linger = 500

[uaparser]
yaml = "../data/ua-parser/regexes.yaml"

[geo_ip]
mmdb = "../data/geo-ip/GeoLite2-Country.mmdb"

[redirect]
not_found_url = "http://localhost:5801/404/{}"
index_url = "http://localhost:5801/index/{}"
