debug = true

[aws]
local = true
localstack_endpoint="http://localhost:4566"

[aws.dynamo]
encryption_table = "core-routes-encryption-local"
routes_table = "core-routes-local"
hostname_mappings_table = "core-routes-hostname-mapping-local"
user_settings_table = "core-user-settings-local"

[kafka]
[kafka.hit_stream]
topic = "hit-stream-main"
hosts = ["localhost"]
ack_timeout_secs = 60
batch_size = 100
consumers_count = 2
iteration_seconds = 1

[uaparser]
yaml = "./data/ua-parser/regexes.yaml"

[geo_ip]
mmdb = "./data/geo-ip/GeoLite2-Country.mmdb"