version: "3.8"
include:
  - ../../redirect/docker-compose.yml
  - ../../api/docker-compose.yml
  - ../../ui/docker-compose.yml

networks:
  shortas-net:
    driver: bridge
    external: false

services:
  db:
    image: postgres:16.2
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ${PWD}/fs/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shortas-net
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - ./keycloak/keycloak-theme:/opt/keycloak/themes/shortas/login:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shortas-net
    restart: unless-stopped

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ${PWD}/fs/vault_data:/vault/file # For persistent file storage
      - ${PWD}/fs/config:/vault/config # For mounting custom configuration files
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroottoken" # For development mode, not recommended for production
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK # Required for Vault's memory locking
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shortas-net
