[kafka]
[kafka.click_stream]
topic = "click-aggs-local"
hosts = ["localhost:9092", "localhost:9093"]

[fluvio]
[fluvio.click_stream]
topic = "click-aggs-local"
host = "fluvio:9103"
consumer = "click_aggs"

[clickhouse]
[clickhouse.click_stream_store]
url = "http://localhost:8123"
user = "default"
password = "clickhouse"
max_rows = 100_000
period_millis = 100
period_bias = 0.1
database = "shortas"
table = "click_stream"

[server]
threads = 8
listen_os_signals = true
exit = true
