debug = true

[kafka]
[kafka.click_stream]
topic = "click-aggs-local"
hosts = ["kafka:9092", "kafka:9093"]

[fluvio]
[fluvio.click_stream]
topic = "click-aggs-local"
host = "localhost:9103"
consumer = "aggs"

[server]
threads = 8
listen_os_signals = true
exit = true
